//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Btgsa.Cgweb.Proyecto.EntidadNegocio {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("StepDST")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class StepDST : global::System.Data.DataSet {
        
        private EF_STEPDataTable tableEF_STEP;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public StepDST() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected StepDST(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["EF_STEP"] != null)) {
                    base.Tables.Add(new EF_STEPDataTable(ds.Tables["EF_STEP"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public EF_STEPDataTable EF_STEP {
            get {
                return this.tableEF_STEP;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            StepDST cln = ((StepDST)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["EF_STEP"] != null)) {
                    base.Tables.Add(new EF_STEPDataTable(ds.Tables["EF_STEP"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableEF_STEP = ((EF_STEPDataTable)(base.Tables["EF_STEP"]));
            if ((initTable == true)) {
                if ((this.tableEF_STEP != null)) {
                    this.tableEF_STEP.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "StepDST";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/StepDST.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableEF_STEP = new EF_STEPDataTable();
            base.Tables.Add(this.tableEF_STEP);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeEF_STEP() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            StepDST ds = new StepDST();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void EF_STEPRowChangeEventHandler(object sender, EF_STEPRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class EF_STEPDataTable : global::System.Data.TypedTableBase<EF_STEPRow> {
            
            private global::System.Data.DataColumn columnSTEP_FLOW;
            
            private global::System.Data.DataColumn columnSTEP_ID;
            
            private global::System.Data.DataColumn columnSTEP_NAME;
            
            private global::System.Data.DataColumn columnSTEP_DESCRIPTION;
            
            private global::System.Data.DataColumn columnSTEP_NEXT_TYPE;
            
            private global::System.Data.DataColumn columnSTEP_NEXT_VALUE;
            
            private global::System.Data.DataColumn columnSTEP_PREV_TYPE;
            
            private global::System.Data.DataColumn columnSTEP_PREV_VALUE;
            
            private global::System.Data.DataColumn columnSTEP_ASSIGNTO_TYPE;
            
            private global::System.Data.DataColumn columnSTEP_ASSIGNTO_VALUE;
            
            private global::System.Data.DataColumn columnSTEP_ASSIGNTO_ALGORITHM;
            
            private global::System.Data.DataColumn columnSTEP_STATUS;
            
            private global::System.Data.DataColumn columnSTEP_PERCENT_WEIGHT;
            
            private global::System.Data.DataColumn columnSTEP_DURATION;
            
            private global::System.Data.DataColumn columnSTEP_START_DATE;
            
            private global::System.Data.DataColumn columnSTEP_LIMIT_DATE;
            
            private global::System.Data.DataColumn columnSTEP_VIEW_METADATA;
            
            private global::System.Data.DataColumn columnSTEP_EDIT_METADATA;
            
            private global::System.Data.DataColumn columnSTEP_ENTER_FUNCTION;
            
            private global::System.Data.DataColumn columnSTEP_EXIT_FUNCTION;
            
            private global::System.Data.DataColumn columnSTEP_ASSIGN_PIC;
            
            private global::System.Data.DataColumn columnSTEP_CHECKLIST;
            
            private global::System.Data.DataColumn columnSTEP_SHOW_HELP;
            
            private global::System.Data.DataColumn columnSTEP_HELP_HTML;
            
            private global::System.Data.DataColumn columnSTEP_CONSOLIDATOR;
            
            private global::System.Data.DataColumn columnSTEP_FORM_TYPE;
            
            private global::System.Data.DataColumn columnSTEP_FORM_VALUE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_STEPDataTable() {
                this.TableName = "EF_STEP";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal EF_STEPDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected EF_STEPDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_FLOWColumn {
                get {
                    return this.columnSTEP_FLOW;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_IDColumn {
                get {
                    return this.columnSTEP_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_NAMEColumn {
                get {
                    return this.columnSTEP_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_DESCRIPTIONColumn {
                get {
                    return this.columnSTEP_DESCRIPTION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_NEXT_TYPEColumn {
                get {
                    return this.columnSTEP_NEXT_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_NEXT_VALUEColumn {
                get {
                    return this.columnSTEP_NEXT_VALUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_PREV_TYPEColumn {
                get {
                    return this.columnSTEP_PREV_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_PREV_VALUEColumn {
                get {
                    return this.columnSTEP_PREV_VALUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_ASSIGNTO_TYPEColumn {
                get {
                    return this.columnSTEP_ASSIGNTO_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_ASSIGNTO_VALUEColumn {
                get {
                    return this.columnSTEP_ASSIGNTO_VALUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_ASSIGNTO_ALGORITHMColumn {
                get {
                    return this.columnSTEP_ASSIGNTO_ALGORITHM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_STATUSColumn {
                get {
                    return this.columnSTEP_STATUS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_PERCENT_WEIGHTColumn {
                get {
                    return this.columnSTEP_PERCENT_WEIGHT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_DURATIONColumn {
                get {
                    return this.columnSTEP_DURATION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_START_DATEColumn {
                get {
                    return this.columnSTEP_START_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_LIMIT_DATEColumn {
                get {
                    return this.columnSTEP_LIMIT_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_VIEW_METADATAColumn {
                get {
                    return this.columnSTEP_VIEW_METADATA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_EDIT_METADATAColumn {
                get {
                    return this.columnSTEP_EDIT_METADATA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_ENTER_FUNCTIONColumn {
                get {
                    return this.columnSTEP_ENTER_FUNCTION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_EXIT_FUNCTIONColumn {
                get {
                    return this.columnSTEP_EXIT_FUNCTION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_ASSIGN_PICColumn {
                get {
                    return this.columnSTEP_ASSIGN_PIC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_CHECKLISTColumn {
                get {
                    return this.columnSTEP_CHECKLIST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_SHOW_HELPColumn {
                get {
                    return this.columnSTEP_SHOW_HELP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_HELP_HTMLColumn {
                get {
                    return this.columnSTEP_HELP_HTML;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_CONSOLIDATORColumn {
                get {
                    return this.columnSTEP_CONSOLIDATOR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_FORM_TYPEColumn {
                get {
                    return this.columnSTEP_FORM_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn STEP_FORM_VALUEColumn {
                get {
                    return this.columnSTEP_FORM_VALUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_STEPRow this[int index] {
                get {
                    return ((EF_STEPRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_STEPRowChangeEventHandler EF_STEPRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_STEPRowChangeEventHandler EF_STEPRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_STEPRowChangeEventHandler EF_STEPRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_STEPRowChangeEventHandler EF_STEPRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddEF_STEPRow(EF_STEPRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_STEPRow AddEF_STEPRow(
                        int STEP_FLOW, 
                        int STEP_ID, 
                        string STEP_NAME, 
                        string STEP_DESCRIPTION, 
                        string STEP_NEXT_TYPE, 
                        string STEP_NEXT_VALUE, 
                        string STEP_PREV_TYPE, 
                        string STEP_PREV_VALUE, 
                        string STEP_ASSIGNTO_TYPE, 
                        string STEP_ASSIGNTO_VALUE, 
                        string STEP_ASSIGNTO_ALGORITHM, 
                        string STEP_STATUS, 
                        double STEP_PERCENT_WEIGHT, 
                        string STEP_DURATION, 
                        System.TimeSpan STEP_START_DATE, 
                        System.TimeSpan STEP_LIMIT_DATE, 
                        int STEP_VIEW_METADATA, 
                        int STEP_EDIT_METADATA, 
                        string STEP_ENTER_FUNCTION, 
                        string STEP_EXIT_FUNCTION, 
                        int STEP_ASSIGN_PIC, 
                        int STEP_CHECKLIST, 
                        int STEP_SHOW_HELP, 
                        string STEP_HELP_HTML, 
                        int STEP_CONSOLIDATOR, 
                        string STEP_FORM_TYPE, 
                        string STEP_FORM_VALUE) {
                EF_STEPRow rowEF_STEPRow = ((EF_STEPRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        STEP_FLOW,
                        STEP_ID,
                        STEP_NAME,
                        STEP_DESCRIPTION,
                        STEP_NEXT_TYPE,
                        STEP_NEXT_VALUE,
                        STEP_PREV_TYPE,
                        STEP_PREV_VALUE,
                        STEP_ASSIGNTO_TYPE,
                        STEP_ASSIGNTO_VALUE,
                        STEP_ASSIGNTO_ALGORITHM,
                        STEP_STATUS,
                        STEP_PERCENT_WEIGHT,
                        STEP_DURATION,
                        STEP_START_DATE,
                        STEP_LIMIT_DATE,
                        STEP_VIEW_METADATA,
                        STEP_EDIT_METADATA,
                        STEP_ENTER_FUNCTION,
                        STEP_EXIT_FUNCTION,
                        STEP_ASSIGN_PIC,
                        STEP_CHECKLIST,
                        STEP_SHOW_HELP,
                        STEP_HELP_HTML,
                        STEP_CONSOLIDATOR,
                        STEP_FORM_TYPE,
                        STEP_FORM_VALUE};
                rowEF_STEPRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowEF_STEPRow);
                return rowEF_STEPRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                EF_STEPDataTable cln = ((EF_STEPDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new EF_STEPDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnSTEP_FLOW = base.Columns["STEP_FLOW"];
                this.columnSTEP_ID = base.Columns["STEP_ID"];
                this.columnSTEP_NAME = base.Columns["STEP_NAME"];
                this.columnSTEP_DESCRIPTION = base.Columns["STEP_DESCRIPTION"];
                this.columnSTEP_NEXT_TYPE = base.Columns["STEP_NEXT_TYPE"];
                this.columnSTEP_NEXT_VALUE = base.Columns["STEP_NEXT_VALUE"];
                this.columnSTEP_PREV_TYPE = base.Columns["STEP_PREV_TYPE"];
                this.columnSTEP_PREV_VALUE = base.Columns["STEP_PREV_VALUE"];
                this.columnSTEP_ASSIGNTO_TYPE = base.Columns["STEP_ASSIGNTO_TYPE"];
                this.columnSTEP_ASSIGNTO_VALUE = base.Columns["STEP_ASSIGNTO_VALUE"];
                this.columnSTEP_ASSIGNTO_ALGORITHM = base.Columns["STEP_ASSIGNTO_ALGORITHM"];
                this.columnSTEP_STATUS = base.Columns["STEP_STATUS"];
                this.columnSTEP_PERCENT_WEIGHT = base.Columns["STEP_PERCENT_WEIGHT"];
                this.columnSTEP_DURATION = base.Columns["STEP_DURATION"];
                this.columnSTEP_START_DATE = base.Columns["STEP_START_DATE"];
                this.columnSTEP_LIMIT_DATE = base.Columns["STEP_LIMIT_DATE"];
                this.columnSTEP_VIEW_METADATA = base.Columns["STEP_VIEW_METADATA"];
                this.columnSTEP_EDIT_METADATA = base.Columns["STEP_EDIT_METADATA"];
                this.columnSTEP_ENTER_FUNCTION = base.Columns["STEP_ENTER_FUNCTION"];
                this.columnSTEP_EXIT_FUNCTION = base.Columns["STEP_EXIT_FUNCTION"];
                this.columnSTEP_ASSIGN_PIC = base.Columns["STEP_ASSIGN_PIC"];
                this.columnSTEP_CHECKLIST = base.Columns["STEP_CHECKLIST"];
                this.columnSTEP_SHOW_HELP = base.Columns["STEP_SHOW_HELP"];
                this.columnSTEP_HELP_HTML = base.Columns["STEP_HELP_HTML"];
                this.columnSTEP_CONSOLIDATOR = base.Columns["STEP_CONSOLIDATOR"];
                this.columnSTEP_FORM_TYPE = base.Columns["STEP_FORM_TYPE"];
                this.columnSTEP_FORM_VALUE = base.Columns["STEP_FORM_VALUE"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnSTEP_FLOW = new global::System.Data.DataColumn("STEP_FLOW", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_FLOW);
                this.columnSTEP_ID = new global::System.Data.DataColumn("STEP_ID", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_ID);
                this.columnSTEP_NAME = new global::System.Data.DataColumn("STEP_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_NAME);
                this.columnSTEP_DESCRIPTION = new global::System.Data.DataColumn("STEP_DESCRIPTION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_DESCRIPTION);
                this.columnSTEP_NEXT_TYPE = new global::System.Data.DataColumn("STEP_NEXT_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_NEXT_TYPE);
                this.columnSTEP_NEXT_VALUE = new global::System.Data.DataColumn("STEP_NEXT_VALUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_NEXT_VALUE);
                this.columnSTEP_PREV_TYPE = new global::System.Data.DataColumn("STEP_PREV_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_PREV_TYPE);
                this.columnSTEP_PREV_VALUE = new global::System.Data.DataColumn("STEP_PREV_VALUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_PREV_VALUE);
                this.columnSTEP_ASSIGNTO_TYPE = new global::System.Data.DataColumn("STEP_ASSIGNTO_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_ASSIGNTO_TYPE);
                this.columnSTEP_ASSIGNTO_VALUE = new global::System.Data.DataColumn("STEP_ASSIGNTO_VALUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_ASSIGNTO_VALUE);
                this.columnSTEP_ASSIGNTO_ALGORITHM = new global::System.Data.DataColumn("STEP_ASSIGNTO_ALGORITHM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_ASSIGNTO_ALGORITHM);
                this.columnSTEP_STATUS = new global::System.Data.DataColumn("STEP_STATUS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_STATUS);
                this.columnSTEP_PERCENT_WEIGHT = new global::System.Data.DataColumn("STEP_PERCENT_WEIGHT", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_PERCENT_WEIGHT);
                this.columnSTEP_DURATION = new global::System.Data.DataColumn("STEP_DURATION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_DURATION);
                this.columnSTEP_START_DATE = new global::System.Data.DataColumn("STEP_START_DATE", typeof(global::System.TimeSpan), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_START_DATE);
                this.columnSTEP_LIMIT_DATE = new global::System.Data.DataColumn("STEP_LIMIT_DATE", typeof(global::System.TimeSpan), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_LIMIT_DATE);
                this.columnSTEP_VIEW_METADATA = new global::System.Data.DataColumn("STEP_VIEW_METADATA", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_VIEW_METADATA);
                this.columnSTEP_EDIT_METADATA = new global::System.Data.DataColumn("STEP_EDIT_METADATA", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_EDIT_METADATA);
                this.columnSTEP_ENTER_FUNCTION = new global::System.Data.DataColumn("STEP_ENTER_FUNCTION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_ENTER_FUNCTION);
                this.columnSTEP_EXIT_FUNCTION = new global::System.Data.DataColumn("STEP_EXIT_FUNCTION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_EXIT_FUNCTION);
                this.columnSTEP_ASSIGN_PIC = new global::System.Data.DataColumn("STEP_ASSIGN_PIC", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_ASSIGN_PIC);
                this.columnSTEP_CHECKLIST = new global::System.Data.DataColumn("STEP_CHECKLIST", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_CHECKLIST);
                this.columnSTEP_SHOW_HELP = new global::System.Data.DataColumn("STEP_SHOW_HELP", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_SHOW_HELP);
                this.columnSTEP_HELP_HTML = new global::System.Data.DataColumn("STEP_HELP_HTML", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_HELP_HTML);
                this.columnSTEP_CONSOLIDATOR = new global::System.Data.DataColumn("STEP_CONSOLIDATOR", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_CONSOLIDATOR);
                this.columnSTEP_FORM_TYPE = new global::System.Data.DataColumn("STEP_FORM_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_FORM_TYPE);
                this.columnSTEP_FORM_VALUE = new global::System.Data.DataColumn("STEP_FORM_VALUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEP_FORM_VALUE);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_STEPRow NewEF_STEPRow() {
                return ((EF_STEPRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new EF_STEPRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(EF_STEPRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.EF_STEPRowChanged != null)) {
                    this.EF_STEPRowChanged(this, new EF_STEPRowChangeEvent(((EF_STEPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.EF_STEPRowChanging != null)) {
                    this.EF_STEPRowChanging(this, new EF_STEPRowChangeEvent(((EF_STEPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.EF_STEPRowDeleted != null)) {
                    this.EF_STEPRowDeleted(this, new EF_STEPRowChangeEvent(((EF_STEPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.EF_STEPRowDeleting != null)) {
                    this.EF_STEPRowDeleting(this, new EF_STEPRowChangeEvent(((EF_STEPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveEF_STEPRow(EF_STEPRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                StepDST ds = new StepDST();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "EF_STEPDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class EF_STEPRow : global::System.Data.DataRow {
            
            private EF_STEPDataTable tableEF_STEP;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal EF_STEPRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableEF_STEP = ((EF_STEPDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_FLOW {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_FLOWColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_FLOW\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_FLOWColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_ID {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_ID\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_NAME {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_NAME\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_DESCRIPTION {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_DESCRIPTIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_DESCRIPTION\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_DESCRIPTIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_NEXT_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_NEXT_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_NEXT_TYPE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_NEXT_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_NEXT_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_NEXT_VALUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_NEXT_VALUE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_NEXT_VALUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_PREV_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_PREV_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_PREV_TYPE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_PREV_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_PREV_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_PREV_VALUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_PREV_VALUE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_PREV_VALUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_ASSIGNTO_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_ASSIGNTO_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_ASSIGNTO_TYPE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_ASSIGNTO_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_ASSIGNTO_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_ASSIGNTO_VALUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_ASSIGNTO_VALUE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_ASSIGNTO_VALUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_ASSIGNTO_ALGORITHM {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_ASSIGNTO_ALGORITHMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_ASSIGNTO_ALGORITHM\' de la tabla \'EF_STEP\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_ASSIGNTO_ALGORITHMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_STATUS {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_STATUSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_STATUS\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_STATUSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public double STEP_PERCENT_WEIGHT {
                get {
                    try {
                        return ((double)(this[this.tableEF_STEP.STEP_PERCENT_WEIGHTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_PERCENT_WEIGHT\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_PERCENT_WEIGHTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_DURATION {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_DURATIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_DURATION\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_DURATIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.TimeSpan STEP_START_DATE {
                get {
                    try {
                        return ((global::System.TimeSpan)(this[this.tableEF_STEP.STEP_START_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_START_DATE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_START_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.TimeSpan STEP_LIMIT_DATE {
                get {
                    try {
                        return ((global::System.TimeSpan)(this[this.tableEF_STEP.STEP_LIMIT_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_LIMIT_DATE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_LIMIT_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_VIEW_METADATA {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_VIEW_METADATAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_VIEW_METADATA\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_VIEW_METADATAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_EDIT_METADATA {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_EDIT_METADATAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_EDIT_METADATA\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_EDIT_METADATAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_ENTER_FUNCTION {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_ENTER_FUNCTIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_ENTER_FUNCTION\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_ENTER_FUNCTIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_EXIT_FUNCTION {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_EXIT_FUNCTIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_EXIT_FUNCTION\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_EXIT_FUNCTIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_ASSIGN_PIC {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_ASSIGN_PICColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_ASSIGN_PIC\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_ASSIGN_PICColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_CHECKLIST {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_CHECKLISTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_CHECKLIST\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_CHECKLISTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_SHOW_HELP {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_SHOW_HELPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_SHOW_HELP\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_SHOW_HELPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_HELP_HTML {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_HELP_HTMLColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_HELP_HTML\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_HELP_HTMLColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int STEP_CONSOLIDATOR {
                get {
                    try {
                        return ((int)(this[this.tableEF_STEP.STEP_CONSOLIDATORColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_CONSOLIDATOR\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_CONSOLIDATORColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_FORM_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_FORM_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_FORM_TYPE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_FORM_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string STEP_FORM_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableEF_STEP.STEP_FORM_VALUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'STEP_FORM_VALUE\' de la tabla \'EF_STEP\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_STEP.STEP_FORM_VALUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_FLOWNull() {
                return this.IsNull(this.tableEF_STEP.STEP_FLOWColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_FLOWNull() {
                this[this.tableEF_STEP.STEP_FLOWColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_IDNull() {
                return this.IsNull(this.tableEF_STEP.STEP_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_IDNull() {
                this[this.tableEF_STEP.STEP_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_NAMENull() {
                return this.IsNull(this.tableEF_STEP.STEP_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_NAMENull() {
                this[this.tableEF_STEP.STEP_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_DESCRIPTIONNull() {
                return this.IsNull(this.tableEF_STEP.STEP_DESCRIPTIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_DESCRIPTIONNull() {
                this[this.tableEF_STEP.STEP_DESCRIPTIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_NEXT_TYPENull() {
                return this.IsNull(this.tableEF_STEP.STEP_NEXT_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_NEXT_TYPENull() {
                this[this.tableEF_STEP.STEP_NEXT_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_NEXT_VALUENull() {
                return this.IsNull(this.tableEF_STEP.STEP_NEXT_VALUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_NEXT_VALUENull() {
                this[this.tableEF_STEP.STEP_NEXT_VALUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_PREV_TYPENull() {
                return this.IsNull(this.tableEF_STEP.STEP_PREV_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_PREV_TYPENull() {
                this[this.tableEF_STEP.STEP_PREV_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_PREV_VALUENull() {
                return this.IsNull(this.tableEF_STEP.STEP_PREV_VALUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_PREV_VALUENull() {
                this[this.tableEF_STEP.STEP_PREV_VALUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_ASSIGNTO_TYPENull() {
                return this.IsNull(this.tableEF_STEP.STEP_ASSIGNTO_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_ASSIGNTO_TYPENull() {
                this[this.tableEF_STEP.STEP_ASSIGNTO_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_ASSIGNTO_VALUENull() {
                return this.IsNull(this.tableEF_STEP.STEP_ASSIGNTO_VALUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_ASSIGNTO_VALUENull() {
                this[this.tableEF_STEP.STEP_ASSIGNTO_VALUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_ASSIGNTO_ALGORITHMNull() {
                return this.IsNull(this.tableEF_STEP.STEP_ASSIGNTO_ALGORITHMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_ASSIGNTO_ALGORITHMNull() {
                this[this.tableEF_STEP.STEP_ASSIGNTO_ALGORITHMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_STATUSNull() {
                return this.IsNull(this.tableEF_STEP.STEP_STATUSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_STATUSNull() {
                this[this.tableEF_STEP.STEP_STATUSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_PERCENT_WEIGHTNull() {
                return this.IsNull(this.tableEF_STEP.STEP_PERCENT_WEIGHTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_PERCENT_WEIGHTNull() {
                this[this.tableEF_STEP.STEP_PERCENT_WEIGHTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_DURATIONNull() {
                return this.IsNull(this.tableEF_STEP.STEP_DURATIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_DURATIONNull() {
                this[this.tableEF_STEP.STEP_DURATIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_START_DATENull() {
                return this.IsNull(this.tableEF_STEP.STEP_START_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_START_DATENull() {
                this[this.tableEF_STEP.STEP_START_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_LIMIT_DATENull() {
                return this.IsNull(this.tableEF_STEP.STEP_LIMIT_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_LIMIT_DATENull() {
                this[this.tableEF_STEP.STEP_LIMIT_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_VIEW_METADATANull() {
                return this.IsNull(this.tableEF_STEP.STEP_VIEW_METADATAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_VIEW_METADATANull() {
                this[this.tableEF_STEP.STEP_VIEW_METADATAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_EDIT_METADATANull() {
                return this.IsNull(this.tableEF_STEP.STEP_EDIT_METADATAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_EDIT_METADATANull() {
                this[this.tableEF_STEP.STEP_EDIT_METADATAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_ENTER_FUNCTIONNull() {
                return this.IsNull(this.tableEF_STEP.STEP_ENTER_FUNCTIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_ENTER_FUNCTIONNull() {
                this[this.tableEF_STEP.STEP_ENTER_FUNCTIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_EXIT_FUNCTIONNull() {
                return this.IsNull(this.tableEF_STEP.STEP_EXIT_FUNCTIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_EXIT_FUNCTIONNull() {
                this[this.tableEF_STEP.STEP_EXIT_FUNCTIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_ASSIGN_PICNull() {
                return this.IsNull(this.tableEF_STEP.STEP_ASSIGN_PICColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_ASSIGN_PICNull() {
                this[this.tableEF_STEP.STEP_ASSIGN_PICColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_CHECKLISTNull() {
                return this.IsNull(this.tableEF_STEP.STEP_CHECKLISTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_CHECKLISTNull() {
                this[this.tableEF_STEP.STEP_CHECKLISTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_SHOW_HELPNull() {
                return this.IsNull(this.tableEF_STEP.STEP_SHOW_HELPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_SHOW_HELPNull() {
                this[this.tableEF_STEP.STEP_SHOW_HELPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_HELP_HTMLNull() {
                return this.IsNull(this.tableEF_STEP.STEP_HELP_HTMLColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_HELP_HTMLNull() {
                this[this.tableEF_STEP.STEP_HELP_HTMLColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_CONSOLIDATORNull() {
                return this.IsNull(this.tableEF_STEP.STEP_CONSOLIDATORColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_CONSOLIDATORNull() {
                this[this.tableEF_STEP.STEP_CONSOLIDATORColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_FORM_TYPENull() {
                return this.IsNull(this.tableEF_STEP.STEP_FORM_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_FORM_TYPENull() {
                this[this.tableEF_STEP.STEP_FORM_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSTEP_FORM_VALUENull() {
                return this.IsNull(this.tableEF_STEP.STEP_FORM_VALUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSTEP_FORM_VALUENull() {
                this[this.tableEF_STEP.STEP_FORM_VALUEColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class EF_STEPRowChangeEvent : global::System.EventArgs {
            
            private EF_STEPRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_STEPRowChangeEvent(EF_STEPRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_STEPRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591