//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Btgsa.Cgweb.Proyecto.EntidadNegocio {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("User")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class UserDST : global::System.Data.DataSet {
        
        private EF_USERDataTable tableEF_USER;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public UserDST() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected UserDST(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["EF_USER"] != null)) {
                    base.Tables.Add(new EF_USERDataTable(ds.Tables["EF_USER"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public EF_USERDataTable EF_USER {
            get {
                return this.tableEF_USER;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            UserDST cln = ((UserDST)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["EF_USER"] != null)) {
                    base.Tables.Add(new EF_USERDataTable(ds.Tables["EF_USER"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableEF_USER = ((EF_USERDataTable)(base.Tables["EF_USER"]));
            if ((initTable == true)) {
                if ((this.tableEF_USER != null)) {
                    this.tableEF_USER.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "User";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/User.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableEF_USER = new EF_USERDataTable();
            base.Tables.Add(this.tableEF_USER);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeEF_USER() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            UserDST ds = new UserDST();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void EF_USERRowChangeEventHandler(object sender, EF_USERRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class EF_USERDataTable : global::System.Data.TypedTableBase<EF_USERRow> {
            
            private global::System.Data.DataColumn columnUSER_ID;
            
            private global::System.Data.DataColumn columnUSER_NAME;
            
            private global::System.Data.DataColumn columnUSER_PASS;
            
            private global::System.Data.DataColumn columnUSER_ROLE;
            
            private global::System.Data.DataColumn columnUSER_AREA;
            
            private global::System.Data.DataColumn columnUSER_BLOCKED;
            
            private global::System.Data.DataColumn columnUSER_ACTIVE;
            
            private global::System.Data.DataColumn columnUSER_IMAGE;
            
            private global::System.Data.DataColumn columnUSER_EMAIL;
            
            private global::System.Data.DataColumn columnUSER_LASTFLOW;
            
            private global::System.Data.DataColumn columnUSER_REPORTS_TO;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_1;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_2;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_3;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_4;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_5;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_6;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_7;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_8;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_9;
            
            private global::System.Data.DataColumn columnUSER_ADDITIONAL_DATA_10;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_USERDataTable() {
                this.TableName = "EF_USER";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal EF_USERDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected EF_USERDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_IDColumn {
                get {
                    return this.columnUSER_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_NAMEColumn {
                get {
                    return this.columnUSER_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_PASSColumn {
                get {
                    return this.columnUSER_PASS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ROLEColumn {
                get {
                    return this.columnUSER_ROLE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_AREAColumn {
                get {
                    return this.columnUSER_AREA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_BLOCKEDColumn {
                get {
                    return this.columnUSER_BLOCKED;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ACTIVEColumn {
                get {
                    return this.columnUSER_ACTIVE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_IMAGEColumn {
                get {
                    return this.columnUSER_IMAGE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_EMAILColumn {
                get {
                    return this.columnUSER_EMAIL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_LASTFLOWColumn {
                get {
                    return this.columnUSER_LASTFLOW;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_REPORTS_TOColumn {
                get {
                    return this.columnUSER_REPORTS_TO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_1Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_2Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_3Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_4Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_4;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_5Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_5;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_6Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_6;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_7Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_7;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_8Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_8;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_9Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_9;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn USER_ADDITIONAL_DATA_10Column {
                get {
                    return this.columnUSER_ADDITIONAL_DATA_10;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_USERRow this[int index] {
                get {
                    return ((EF_USERRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_USERRowChangeEventHandler EF_USERRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_USERRowChangeEventHandler EF_USERRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_USERRowChangeEventHandler EF_USERRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event EF_USERRowChangeEventHandler EF_USERRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddEF_USERRow(EF_USERRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_USERRow AddEF_USERRow(
                        string USER_ID, 
                        string USER_NAME, 
                        string USER_PASS, 
                        string USER_ROLE, 
                        string USER_AREA, 
                        string USER_BLOCKED, 
                        string USER_ACTIVE, 
                        string USER_IMAGE, 
                        string USER_EMAIL, 
                        int USER_LASTFLOW, 
                        string USER_REPORTS_TO, 
                        string USER_ADDITIONAL_DATA_1, 
                        string USER_ADDITIONAL_DATA_2, 
                        string USER_ADDITIONAL_DATA_3, 
                        string USER_ADDITIONAL_DATA_4, 
                        string USER_ADDITIONAL_DATA_5, 
                        string USER_ADDITIONAL_DATA_6, 
                        string USER_ADDITIONAL_DATA_7, 
                        string USER_ADDITIONAL_DATA_8, 
                        string USER_ADDITIONAL_DATA_9, 
                        string USER_ADDITIONAL_DATA_10) {
                EF_USERRow rowEF_USERRow = ((EF_USERRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        USER_ID,
                        USER_NAME,
                        USER_PASS,
                        USER_ROLE,
                        USER_AREA,
                        USER_BLOCKED,
                        USER_ACTIVE,
                        USER_IMAGE,
                        USER_EMAIL,
                        USER_LASTFLOW,
                        USER_REPORTS_TO,
                        USER_ADDITIONAL_DATA_1,
                        USER_ADDITIONAL_DATA_2,
                        USER_ADDITIONAL_DATA_3,
                        USER_ADDITIONAL_DATA_4,
                        USER_ADDITIONAL_DATA_5,
                        USER_ADDITIONAL_DATA_6,
                        USER_ADDITIONAL_DATA_7,
                        USER_ADDITIONAL_DATA_8,
                        USER_ADDITIONAL_DATA_9,
                        USER_ADDITIONAL_DATA_10};
                rowEF_USERRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowEF_USERRow);
                return rowEF_USERRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_USERRow FindByUSER_ID(string USER_ID) {
                return ((EF_USERRow)(this.Rows.Find(new object[] {
                            USER_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                EF_USERDataTable cln = ((EF_USERDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new EF_USERDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnUSER_ID = base.Columns["USER_ID"];
                this.columnUSER_NAME = base.Columns["USER_NAME"];
                this.columnUSER_PASS = base.Columns["USER_PASS"];
                this.columnUSER_ROLE = base.Columns["USER_ROLE"];
                this.columnUSER_AREA = base.Columns["USER_AREA"];
                this.columnUSER_BLOCKED = base.Columns["USER_BLOCKED"];
                this.columnUSER_ACTIVE = base.Columns["USER_ACTIVE"];
                this.columnUSER_IMAGE = base.Columns["USER_IMAGE"];
                this.columnUSER_EMAIL = base.Columns["USER_EMAIL"];
                this.columnUSER_LASTFLOW = base.Columns["USER_LASTFLOW"];
                this.columnUSER_REPORTS_TO = base.Columns["USER_REPORTS_TO"];
                this.columnUSER_ADDITIONAL_DATA_1 = base.Columns["USER_ADDITIONAL_DATA_1"];
                this.columnUSER_ADDITIONAL_DATA_2 = base.Columns["USER_ADDITIONAL_DATA_2"];
                this.columnUSER_ADDITIONAL_DATA_3 = base.Columns["USER_ADDITIONAL_DATA_3"];
                this.columnUSER_ADDITIONAL_DATA_4 = base.Columns["USER_ADDITIONAL_DATA_4"];
                this.columnUSER_ADDITIONAL_DATA_5 = base.Columns["USER_ADDITIONAL_DATA_5"];
                this.columnUSER_ADDITIONAL_DATA_6 = base.Columns["USER_ADDITIONAL_DATA_6"];
                this.columnUSER_ADDITIONAL_DATA_7 = base.Columns["USER_ADDITIONAL_DATA_7"];
                this.columnUSER_ADDITIONAL_DATA_8 = base.Columns["USER_ADDITIONAL_DATA_8"];
                this.columnUSER_ADDITIONAL_DATA_9 = base.Columns["USER_ADDITIONAL_DATA_9"];
                this.columnUSER_ADDITIONAL_DATA_10 = base.Columns["USER_ADDITIONAL_DATA_10"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnUSER_ID = new global::System.Data.DataColumn("USER_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ID);
                this.columnUSER_NAME = new global::System.Data.DataColumn("USER_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_NAME);
                this.columnUSER_PASS = new global::System.Data.DataColumn("USER_PASS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_PASS);
                this.columnUSER_ROLE = new global::System.Data.DataColumn("USER_ROLE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ROLE);
                this.columnUSER_AREA = new global::System.Data.DataColumn("USER_AREA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_AREA);
                this.columnUSER_BLOCKED = new global::System.Data.DataColumn("USER_BLOCKED", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_BLOCKED);
                this.columnUSER_ACTIVE = new global::System.Data.DataColumn("USER_ACTIVE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ACTIVE);
                this.columnUSER_IMAGE = new global::System.Data.DataColumn("USER_IMAGE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_IMAGE);
                this.columnUSER_EMAIL = new global::System.Data.DataColumn("USER_EMAIL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_EMAIL);
                this.columnUSER_LASTFLOW = new global::System.Data.DataColumn("USER_LASTFLOW", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_LASTFLOW);
                this.columnUSER_REPORTS_TO = new global::System.Data.DataColumn("USER_REPORTS_TO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_REPORTS_TO);
                this.columnUSER_ADDITIONAL_DATA_1 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_1);
                this.columnUSER_ADDITIONAL_DATA_2 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_2);
                this.columnUSER_ADDITIONAL_DATA_3 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_3);
                this.columnUSER_ADDITIONAL_DATA_4 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_4", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_4);
                this.columnUSER_ADDITIONAL_DATA_5 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_5", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_5);
                this.columnUSER_ADDITIONAL_DATA_6 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_6", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_6);
                this.columnUSER_ADDITIONAL_DATA_7 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_7", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_7);
                this.columnUSER_ADDITIONAL_DATA_8 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_8", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_8);
                this.columnUSER_ADDITIONAL_DATA_9 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_9", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_9);
                this.columnUSER_ADDITIONAL_DATA_10 = new global::System.Data.DataColumn("USER_ADDITIONAL_DATA_10", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSER_ADDITIONAL_DATA_10);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("EF_USERKey1", new global::System.Data.DataColumn[] {
                                this.columnUSER_ID}, true));
                this.columnUSER_ID.AllowDBNull = false;
                this.columnUSER_ID.Unique = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_USERRow NewEF_USERRow() {
                return ((EF_USERRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new EF_USERRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(EF_USERRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.EF_USERRowChanged != null)) {
                    this.EF_USERRowChanged(this, new EF_USERRowChangeEvent(((EF_USERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.EF_USERRowChanging != null)) {
                    this.EF_USERRowChanging(this, new EF_USERRowChangeEvent(((EF_USERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.EF_USERRowDeleted != null)) {
                    this.EF_USERRowDeleted(this, new EF_USERRowChangeEvent(((EF_USERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.EF_USERRowDeleting != null)) {
                    this.EF_USERRowDeleting(this, new EF_USERRowChangeEvent(((EF_USERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveEF_USERRow(EF_USERRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                UserDST ds = new UserDST();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "EF_USERDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class EF_USERRow : global::System.Data.DataRow {
            
            private EF_USERDataTable tableEF_USER;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal EF_USERRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableEF_USER = ((EF_USERDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ID {
                get {
                    return ((string)(this[this.tableEF_USER.USER_IDColumn]));
                }
                set {
                    this[this.tableEF_USER.USER_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_NAME {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_NAME\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_PASS {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_PASSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_PASS\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_PASSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ROLE {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ROLEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ROLE\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ROLEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_AREA {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_AREAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_AREA\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_AREAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_BLOCKED {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_BLOCKEDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_BLOCKED\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_BLOCKEDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ACTIVE {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ACTIVEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ACTIVE\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ACTIVEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_IMAGE {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_IMAGEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_IMAGE\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_IMAGEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_EMAIL {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_EMAILColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_EMAIL\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_EMAILColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int USER_LASTFLOW {
                get {
                    try {
                        return ((int)(this[this.tableEF_USER.USER_LASTFLOWColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_LASTFLOW\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_LASTFLOWColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_REPORTS_TO {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_REPORTS_TOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_REPORTS_TO\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_REPORTS_TOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_1 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_1\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_2 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_2\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_3 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_3\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_4 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_4Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_4\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_4Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_5 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_5Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_5\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_5Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_6 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_6Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_6\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_6Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_7 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_7Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_7\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_7Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_8 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_8Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_8\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_8Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_9 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_9Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_9\' de la tabla \'EF_USER\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_9Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string USER_ADDITIONAL_DATA_10 {
                get {
                    try {
                        return ((string)(this[this.tableEF_USER.USER_ADDITIONAL_DATA_10Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'USER_ADDITIONAL_DATA_10\' de la tabla \'EF_USER\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableEF_USER.USER_ADDITIONAL_DATA_10Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_NAMENull() {
                return this.IsNull(this.tableEF_USER.USER_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_NAMENull() {
                this[this.tableEF_USER.USER_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_PASSNull() {
                return this.IsNull(this.tableEF_USER.USER_PASSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_PASSNull() {
                this[this.tableEF_USER.USER_PASSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ROLENull() {
                return this.IsNull(this.tableEF_USER.USER_ROLEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ROLENull() {
                this[this.tableEF_USER.USER_ROLEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_AREANull() {
                return this.IsNull(this.tableEF_USER.USER_AREAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_AREANull() {
                this[this.tableEF_USER.USER_AREAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_BLOCKEDNull() {
                return this.IsNull(this.tableEF_USER.USER_BLOCKEDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_BLOCKEDNull() {
                this[this.tableEF_USER.USER_BLOCKEDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ACTIVENull() {
                return this.IsNull(this.tableEF_USER.USER_ACTIVEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ACTIVENull() {
                this[this.tableEF_USER.USER_ACTIVEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_IMAGENull() {
                return this.IsNull(this.tableEF_USER.USER_IMAGEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_IMAGENull() {
                this[this.tableEF_USER.USER_IMAGEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_EMAILNull() {
                return this.IsNull(this.tableEF_USER.USER_EMAILColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_EMAILNull() {
                this[this.tableEF_USER.USER_EMAILColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_LASTFLOWNull() {
                return this.IsNull(this.tableEF_USER.USER_LASTFLOWColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_LASTFLOWNull() {
                this[this.tableEF_USER.USER_LASTFLOWColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_REPORTS_TONull() {
                return this.IsNull(this.tableEF_USER.USER_REPORTS_TOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_REPORTS_TONull() {
                this[this.tableEF_USER.USER_REPORTS_TOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_1Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_1Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_2Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_2Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_3Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_3Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_4Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_4Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_4Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_4Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_5Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_5Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_5Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_5Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_6Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_6Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_6Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_6Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_7Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_7Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_7Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_7Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_8Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_8Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_8Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_8Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_9Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_9Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_9Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_9Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsUSER_ADDITIONAL_DATA_10Null() {
                return this.IsNull(this.tableEF_USER.USER_ADDITIONAL_DATA_10Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetUSER_ADDITIONAL_DATA_10Null() {
                this[this.tableEF_USER.USER_ADDITIONAL_DATA_10Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class EF_USERRowChangeEvent : global::System.EventArgs {
            
            private EF_USERRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_USERRowChangeEvent(EF_USERRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public EF_USERRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591